### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by DaSniper12** [linux-man/p5.tiledmap#4]
Will you be updating this library to work with the latest Tiled Version?

**Comment by linux-man** [comment]
I should! You can help me being a little more precise. Have you problems loading maps? What functionalities do you miss the most?

**Comment by linux-man** [comment]
I noticed something happened starting with 0.5.12. I'm looking into it.

**Comment by linux-man** [comment]
Map preload wasn't working because "Direct calls to _decrementPreload from all loading functions" is needed since 0.5.12.
Updated to the latest p5.js version.

**Comment by DaSniper12** [comment]
I can't really do anything, do you want me to share my repo, like put my code on GitHub for you to see?
I can't preload a map, well I can and it doesn't show any errors, but it doesn't create an object for tmap, (since tmap is the variable to which I upload the tiled map).

**Comment by linux-man** [comment]
Yes, please. Could you zip it and attach to a post or mail me?

**Comment by DaSniper12** [comment]
I sent it to your hotmail email, have you received it?

**Comment by DaSniper12** [comment]
This is the error I am getting, and I am also getting this on the second to last commit you made, http://prntscr.com/jzohu3

**Comment by linux-man** [comment]
For the record:
Calling order of scripts is important p5.js -> Maps -> p5.tiledmap -> Script.
Use latest p5.js version.
Tile Layer Format must be CSV.
Embed all external tilesets.
Study the examples.
All public methods are documented on source code.

**Comment by DaSniper12** [comment]
Could you please try to replicate this on the project that I sent you since I can't figure this out at all?
