### ISSUE TITLE
Create a Documentation 

### ISSUE THREAD

**Issue by M001T** [linux-man/p5.tiledmap#7]
Pls ?

**Comment by linux-man** [comment]
Really? Don't you know how we coders HATE to write documentation? :rofl: 
Don't hold your breathe, but I'll start a wiki.
Soon...
Just don't close this issue until then.

**Comment by linux-man** [comment]
You were not forgotten! Starting a wiki.

**Comment by linux-man** [comment]
It's a WIP, but the beginning was the hardest part.
